"""Export the DMC chart from the .xlsx into a TypeScript module.

The browser engine needs the 589 thread colours, and the colours only exist as
cell *fill* colours in column C — pandas can't see them, only openpyxl can. So
this runs once, offline, and commits the result.

    .venv/Scripts/python.exe scripts/export-dmc.py

Re-run it if DMCcharts2025.xlsx changes.
"""

import os
import sys

import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XLSX = os.path.join(ROOT, "PythonDCA", "DMCcharts2025.xlsx")
OUT = os.path.join(ROOT, "frontend", "src", "engine", "dmc-data.ts")
OUT_PY = os.path.join(ROOT, "PythonDCA", "api", "dmc_colors.py")
OUT_MARK = os.path.join(ROOT, "frontend", "src", "components", "brand", "mark-palette.ts")

# The twelve threads a member's mark is stitched in.
#
# Real references, spread around the hue wheel and all mid-to-deep so no two ever
# come out as a pair of near-identical pastels. This list used to live in
# stitch-avatar.tsx, which resolved it through the bundled chart at module load.
# That was correct and it cost every visitor all 589 threads plus the lookup index
# in the first bundle, to paint twelve colours in a 36px square — StitchAvatar is
# in the site header, so it can never be lazy. Resolved here instead, in the same
# pass as everything else, which leaves the guarantee that mattered untouched:
# these are the colours the patterns use, out of the same spreadsheet.
MARK_CODES = [
    "347",
    "3810",
    "3820",
    "987",
    "3835",
    "798",
    "921",
    "3363",
    "3607",
    "3846",
    "832",
    "3746",
]


def main() -> int:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb.active

    rows = []
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        number, name, swatch = row[0], row[1], row[2]
        fill = swatch.fill
        if not fill or fill.fgColor.type != "rgb":
            print(f"  skipped row {swatch.row}: no rgb fill", file=sys.stderr)
            continue
        hex6 = fill.fgColor.rgb[2:].upper()
        code = str(number.value).strip()
        label = str(name.value).strip().replace("|", "/")
        rows.append(f"{code}|{label}|{hex6}")

    # One long string beats 589 object literals: about a third of the bytes,
    # and the parse is a couple of split() calls at module load.
    body = "\\n".join(rows)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "// GENERATED by scripts/export-dmc.py — do not edit by hand.\n"
            f"// {len(rows)} DMC threads, from PythonDCA/DMCcharts2025.xlsx.\n"
            "// Format per line: number|name|RRGGBB\n\n"
            f'export const DMC_RAW =\n  "{body}"\n'
        )

    size = os.path.getsize(OUT)
    print(f"wrote {OUT}")
    print(f"  {len(rows)} threads, {size / 1024:.1f} KB")

    # The same table for the server.
    #
    # It needs it for exactly one thing: drawing a share card for a published piece.
    # The database stores a grid of thread *codes*, so without the colours the server
    # cannot turn a piece into a picture — and a social scraper does not run the
    # JavaScript that would otherwise do it.
    #
    # Generated from the same spreadsheet in the same pass rather than copied, so the
    # two cannot disagree: whatever regenerates one regenerates the other.
    with open(OUT_PY, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            '"""GENERATED by scripts/export-dmc.py — do not edit by hand.\n\n'
            f"{len(rows)} DMC threads from PythonDCA/DMCcharts2025.xlsx, as RGB.\n"
            "The server uses these to render a piece's share card; the browser reads the\n"
            "same data from frontend/src/engine/dmc-data.ts.\n"
            '"""\n\n'
            "DMC_RGB: dict[str, tuple[int, int, int]] = {\n"
        )
        for line in rows:
            code, _, hex6 = line.split("|")
            r, g, b = (int(hex6[i : i + 2], 16) for i in (0, 2, 4))
            fh.write(f'    "{code.lower()}": ({r}, {g}, {b}),\n')
        fh.write("}\n")

    print(f"wrote {OUT_PY}")
    print(f"  {os.path.getsize(OUT_PY) / 1024:.1f} KB")

    # And the twelve colours a member's mark is stitched in — see MARK_CODES.
    by_code = {}
    for line in rows:
        code, _, hex6 = line.split("|")
        by_code[code.lower()] = hex6
    missing = [c for c in MARK_CODES if c.lower() not in by_code]
    if missing:
        # Loudly, and without writing: a mark palette silently short of a colour
        # would change the marks of everyone whose hash landed past it.
        print(f"  MARK_CODES missing from the spreadsheet: {missing}", file=sys.stderr)
        return 1

    with open(OUT_MARK, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "// GENERATED by scripts/export-dmc.py \u2014 do not edit by hand.\n"
            "//\n"
            "// The threads a member's mark is stitched in, resolved from the same\n"
            "// spreadsheet as the full chart. Generated rather than looked up at runtime\n"
            "// because StitchAvatar sits in the site header: it is in the bundle every\n"
            "// visitor downloads first, and asking the chart for twelve colours put all\n"
            "// 589 threads there with it. The codes, and why those twelve, are in\n"
            "// MARK_CODES in the generator.\n\n"
            "export type MarkThread = { hex: string; rgb: readonly [number, number, number] }\n\n"
            "export const MARK_PALETTE: readonly MarkThread[] = [\n"
        )
        for code in MARK_CODES:
            hex6 = by_code[code.lower()]
            r, g, b = (int(hex6[i : i + 2], 16) for i in (0, 2, 4))
            fh.write(f'  {{ hex: "#{hex6}", rgb: [{r}, {g}, {b}] }}, // DMC {code}\n')
        fh.write("]\n")

    print(f"wrote {OUT_MARK}")
    print(f"  {len(MARK_CODES)} threads, {os.path.getsize(OUT_MARK) / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
