"""Export the DMC chart from the .xlsx into a TypeScript module.

The browser engine needs the 589 thread colours, and the colours only exist as
cell *fill* colours in column C — pandas can't see them, only openpyxl can. So
this runs once, offline, and commits the result.

    .venv/Scripts/python.exe scripts/export-dmc.py

Re-run it if DMCcharts2025.xlsx changes.
"""

import os
import sys

import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XLSX = os.path.join(ROOT, "PythonDCA", "DMCcharts2025.xlsx")
OUT = os.path.join(ROOT, "frontend", "src", "engine", "dmc-data.ts")
OUT_PY = os.path.join(ROOT, "PythonDCA", "api", "dmc_colors.py")


def main() -> int:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    ws = wb.active

    rows = []
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        number, name, swatch = row[0], row[1], row[2]
        fill = swatch.fill
        if not fill or fill.fgColor.type != "rgb":
            print(f"  skipped row {swatch.row}: no rgb fill", file=sys.stderr)
            continue
        hex6 = fill.fgColor.rgb[2:].upper()
        code = str(number.value).strip()
        label = str(name.value).strip().replace("|", "/")
        rows.append(f"{code}|{label}|{hex6}")

    # One long string beats 589 object literals: about a third of the bytes,
    # and the parse is a couple of split() calls at module load.
    body = "\\n".join(rows)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "// GENERATED by scripts/export-dmc.py — do not edit by hand.\n"
            f"// {len(rows)} DMC threads, from PythonDCA/DMCcharts2025.xlsx.\n"
            "// Format per line: number|name|RRGGBB\n\n"
            f'export const DMC_RAW =\n  "{body}"\n'
        )

    size = os.path.getsize(OUT)
    print(f"wrote {OUT}")
    print(f"  {len(rows)} threads, {size / 1024:.1f} KB")

    # The same table for the server.
    #
    # It needs it for exactly one thing: drawing a share card for a published piece.
    # The database stores a grid of thread *codes*, so without the colours the server
    # cannot turn a piece into a picture — and a social scraper does not run the
    # JavaScript that would otherwise do it.
    #
    # Generated from the same spreadsheet in the same pass rather than copied, so the
    # two cannot disagree: whatever regenerates one regenerates the other.
    with open(OUT_PY, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            '"""GENERATED by scripts/export-dmc.py — do not edit by hand.\n\n'
            f"{len(rows)} DMC threads from PythonDCA/DMCcharts2025.xlsx, as RGB.\n"
            "The server uses these to render a piece's share card; the browser reads the\n"
            "same data from frontend/src/engine/dmc-data.ts.\n"
            '"""\n\n'
            "DMC_RGB: dict[str, tuple[int, int, int]] = {\n"
        )
        for line in rows:
            code, _, hex6 = line.split("|")
            r, g, b = (int(hex6[i : i + 2], 16) for i in (0, 2, 4))
            fh.write(f'    "{code.lower()}": ({r}, {g}, {b}),\n')
        fh.write("}\n")

    print(f"wrote {OUT_PY}")
    print(f"  {os.path.getsize(OUT_PY) / 1024:.1f} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
