// GENERATED by scripts/export-dmc.py — do not edit by hand.
//
// The threads a member's mark is stitched in, resolved from the same
// spreadsheet as the full chart. Generated rather than looked up at runtime
// because StitchAvatar sits in the site header: it is in the bundle every
// visitor downloads first, and asking the chart for twelve colours put all
// 589 threads there with it. The codes, and why those twelve, are in
// MARK_CODES in the generator.

export type MarkThread = { hex: string; rgb: readonly [number, number, number] }

export const MARK_PALETTE: readonly MarkThread[] = [
  { hex: "#AB1B33", rgb: [171, 27, 51] }, // DMC 347
  { hex: "#2D8D98", rgb: [45, 141, 152] }, // DMC 3810
  { hex: "#DBA53E", rgb: [219, 165, 62] }, // DMC 3820
  { hex: "#436838", rgb: [67, 104, 56] }, // DMC 987
  { hex: "#924D78", rgb: [146, 77, 120] }, // DMC 3835
  { hex: "#4E5CA7", rgb: [78, 92, 167] }, // DMC 798
  { hex: "#C0573D", rgb: [192, 87, 61] }, // DMC 921
  { hex: "#617451", rgb: [97, 116, 81] }, // DMC 3363
  { hex: "#D94C9D", rgb: [217, 76, 157] }, // DMC 3607
  { hex: "#5ECCEC", rgb: [94, 204, 236] }, // DMC 3846
  { hex: "#9C7230", rgb: [156, 114, 48] }, // DMC 832
  { hex: "#844AB5", rgb: [132, 74, 181] }, // DMC 3746
]
